name: softgym
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.17.2
  - imageio=2.6.1
  - glob2=0.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - click
  - matplotlib
  - joblib
  - Pillow=6.1
  - plotly=2.0
# SoftAgent specific
  - pip:
      - torch==1.7.1
      - torchvision
      - dm-env
      - dm-tree
      - termcolor
      - scikit-image
      - kornia